config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'signin', to: 'session#signin'
  post 'session/create', to: 'session#create'
  delete 'logout', to: 'session#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get  '/users/new',  to: 'users#new'
  # get  'users/show/:id', to: 'users#show'
  # post '/users', to: 'users#create'
  # patch 'events/:id', to: 'event#update'
  resources :users
  resources :events do
    member do 
     post :attendee
    end
  end

  # patch 'events/:id/attend', to: 'event#attend_events'

  root 'users#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :attendees, through: :attendances
  validates :name, presence: true
  validates :location, presence: true
  validates :event_date, presence: true
  scope :past, -> { where('event_date <= (?)', DateTime.now) }
  scope :future, -> { where('event_date > (?)', DateTime.now) }

  def attended_event?(user)
    attendees.include?(user)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events
  has_many :attendances
  has_many :attended_events, through: :attendances, class_name: 'Events'
  validates :name, presence: true
  validates :email, presence: true

  def upcoming_events
    future_events = []
    attendances.each do |event|
      a = Event.find_by(id: event.event_id)
      future_events << a if a.event_date > DateTime.now
    end
    future_events
  end

  def previous_events
    past_events = []
    attendances.each do |event|
      a = Event.find_by(id: event.event_id)
      past_events << a if a.event_date < DateTime.now
    end
    past_events
    # attendances.where("event_date < DateTime.now")
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if (user_id = session[:user_id])
      @user ||= User.find(user_id)
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :require_login, only: %i[new create]
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(name: params[:event][:name], location: params[:event][:location], event_date: params[:event][:event_date])
    @event.build_user(id: session[:user_id])
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def index
    @past_events = Event.past
    @future_events = Event.future
  end

  def attendee
    event = Event.find_by(id: params[:event_id])
    event.attendances.create(user_id: current_user.id)
    redirect_to show
  end

  private

  def require_login
    redirect_to root_path unless logged_in?
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  def signin
    @user = User.new
  end

  def create
    # puts params
    user = User.find_by(email: params[:email])
    if user
      log_in user
      redirect_to user
    else
      @user = User.new
      render 'session/signin'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def log_out
    session.delete(:user_id)
    cookies.delete(:user_id)
    @user = nil
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Welcome to our private events platform'
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def signin(user)
    session[:user_id] = user.id
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Private events'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/index.html.erb
<h2>Past events</h2>
<ul>
<% @past_events.each do |event| %>
  <li><%= link_to event.name, event_path(event.id) %> on <%= event.event_date %></li>
<% end %>
</ul>
<h2>Future events</h2>
<ul>
<% @future_events.each do |event| %>
  <li><%= link_to event.name, event_path(event.id) %> on <%= event.event_date %></li>
<% end %>
</ul>

app/views/events/new.html.erb
<% provide(:title, "Create new Event") %>
<h1>Create a new event</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= f.label :description %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :event_date %>
      <%= f.date_field :event_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
      <%= f.submit "Create event", class: "btn btn-primary" %>
    <% end%>
  </div>
</div>

app/views/events/show.html.erb
<h1>Event information</h1>
<p>Event Creator: <%= @event.user.name %></p>
<% unless @event.attended_event?(current_user) %>
<div class="row">
  <div class="md-8">
    <%= form_with(method: 'post', url: attendee_event_path)  do %>
      <%= submit_tag "Attend", class: "btn btn-primary" %>
      <%= hidden_field_tag(:event_id, @event.id) %>
    <% end %>
  </div>
</div>
<% end %>
<h2>Attendees</h2>
<ul>
  <% @event.attendees.each do |a| %>
    <li><%= a.name %></li>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Private event ", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "My Events", user_path(1) %></li>
            <li><%= link_to "Events", events_path %></li>
            <% if  logged_in? %>
            <li><%= link_to "New Event", new_event_path %></li>
            <% end %>
            <% if  logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", signin_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>

    </div>
  </body>
</html>

app/views/session/signin.html.erb
<% provide(:title, "Sign In") %>
<h1>User Sign In</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(url: session_create_path, method: "post" ) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Sign In", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Please fix the following <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "User registration") %>
<h1>User Registration</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Sing up", class: "btn btn-primary", id: "button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User info') %>
<h1>Showing <%= @user.name %> information</h1>

<h2>My events</h2>
<ul>
  <% @user.events.each do |event| %>
    <li><%= event.name %></li>
  <% end %>
</ul>

<h2>Attended events</h2>
<ul>
<% @user.previous_events.each do |event| %>
  <li><%= event.name %></li>
<% end %>
</ul>

<h2>Upcoming events</h2>
<ul>
<% @user.upcoming_events.each do |event| %>
  <li><%= event.name %></li>
<% end %>
</ul>

app/views/users/signin.html.erb
<% provide(:title, "Sign In") %>
<h1>User Sign In</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Sign In", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>